name: medimage

channels:
  - conda-forge
  - defaults
dependencies:
  - Deprecated==1.2.13
  - matplotlib==3.4.2
  - nibabel==3.2.1
  - numpy==1.20.0
  - Pillow==9.1.0
  - PyWavelets==1.1.1
  - scikit-image==0.18.2
  - scipy==1.7.0
  - ipykernel
  - pip
  - pip:
    - SimpleITK==2.1.1.2
    - pandas==1.2.1
    - numpyencoder==0.3.0
    - pdoc3
